// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: ping.proto

package pbfixtures

import (
	"context"

	"google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	PingService_Ping_FullMethodName       = "/testutil.PingService/Ping"
	PingService_PingStream_FullMethodName = "/testutil.PingService/PingStream"
)

// PingServiceClient is the client API for PingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	PingStream(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (PingService_PingStreamClient, error)
}

type pingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPingServiceClient(cc grpc.ClientConnInterface) PingServiceClient {
	_ = "STUB: not implemented"
	return *new(PingServiceClient)
}

func (c *pingServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *pingServiceClient) PingStream(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (PingService_PingStreamClient, error) {
	_ = "STUB: not implemented"
	return *new(PingService_PingStreamClient), nil
}

type PingService_PingStreamClient interface {
	Recv() (*PingResponse, error)
	grpc.ClientStream
}

type pingServicePingStreamClient struct {
	grpc.ClientStream
}

func (x *pingServicePingStreamClient) Recv() (*PingResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PingServiceServer is the server API for PingService service.
// All implementations must embed UnimplementedPingServiceServer
// for forward compatibility
type PingServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	PingStream(*PingRequest, PingService_PingStreamServer) error
	mustEmbedUnimplementedPingServiceServer()
}

// UnimplementedPingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPingServiceServer struct {
}

func (UnimplementedPingServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedPingServiceServer) PingStream(*PingRequest, PingService_PingStreamServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (UnimplementedPingServiceServer) mustEmbedUnimplementedPingServiceServer() {
	_ = "STUB: not implemented"

	// UnsafePingServiceServer may be embedded to opt out of forward compatibility for this service.
	// Use of this interface is not recommended, as added methods to PingServiceServer will
	// result in compilation errors.
	return
}

type UnsafePingServiceServer interface {
	mustEmbedUnimplementedPingServiceServer()
}

func RegisterPingServiceServer(s grpc.ServiceRegistrar, srv PingServiceServer) {
	_ = "STUB: not implemented"
	return
}

func _PingService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _PingService_PingStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type PingService_PingStreamServer interface {
	Send(*PingResponse) error
	grpc.ServerStream
}

type pingServicePingStreamServer struct {
	grpc.ServerStream
}

func (x *pingServicePingStreamServer) Send(m *PingResponse) error {
	_ = "STUB: not implemented"
	return nil
}

// PingService_ServiceDesc is the grpc.ServiceDesc for PingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "testutil.PingService",
	HandlerType: (*PingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PingService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PingStream",
			Handler:       _PingService_PingStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ping.proto",
}
